### ISSUE TITLE
Thoughts on organizations for courses that repeat

### ISSUE THREAD

**Issue by brock** [education/teachers#31]
I've read through the Github Training guide, and am curious to hear how educators are using Github Organizations for courses that repeat.

I have a number of questions, but would love to hear any general information from your experience that relates to the way you structure your courses as Github Organizations, with as much detail as you'd care to share.

* Do you prefer organizations like `School-CourseNumber` or `School-CourseNumber-Semester`?
* Do you prefer private repos to public repos in one case over the other?
* How do you communicate with students about their use of other's code?
* Do you find yourself revising course materials and assignments each semester? And does this differ for private or public repos?

**Comment by thomasjbradley** [comment]
I don't use the structure that GitHub suggests for handing in assignments because my course is just one of many in a whole program—the only code writing course. So in order for everything to remain consistent everything gets handed in to [Instructure Canvas](http://www.instructure.com/).

The students create repos and websites on GitHub, set up `gh-pages`, then submit that URL to Canvas.

But, to address some of your other questions:

> Do you prefer private repos to public repos in one case over the other?

We only use public repositories—all the students’ code is completely open and visible to everybody else.

> How do you communicate with students about their use of other's code?

That, of course, leads to this question, and really it hasn’t ever been a problem.
We talk about copyright & licensing (MIT, GPL, etc.), but we don’t have problems with students copying from each other. Primarily I think it’s because they need to design everything differently from each other anyways.

Generally, it’s kind of a security through obscurity thing: none of the students really know each others’ GitHub usernames and don’t put in the effort to go looking for it.

Our program really follows “do to learn” and it becomes painfully obvious when the students aren’t doing the work themselves.

The bigger problem we have is just copying-pasting from tutorials sites like Codrops. Which I just call them out on and give them a 0 on the grade.
